<a href="https://colab.research.google.com/github/KushanNalinka/NLPTranslator/blob/main/KMProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
data = pd.read_csv('eng_-french.csv')

In [5]:
data

English words/sentences                 French words/sentences
0                            Hi.                                 Salut!
1                           Run!                                Cours !
2                           Run!                               Courez !
3                           Who?                                  Qui ?
4                           Wow!                             Ça alors !
...                          ...                                    ...
64927  We grew closer every day.     Nous nous approchâmes chaque jour.
64928  We had a storm yesterday.   Nous avons essuyé une tempête, hier.
64929  We had fun at Disneyland.  Nous nous sommes amusés à Disneyland.
64930  We had lots of fun today.   On s'est beaucoup amusé aujourd'hui.
64931       We had no drinking w                                    NaN

[64932 rows x 2 columns]

In [6]:
data['English words/sentences count'] = data['English words/sentences'].str.split().str.len()

In [7]:
data['English words/sentences'].str.split()

0                                   [Hi.]
1                                  [Run!]
2                                  [Run!]
3                                  [Who?]
4                                  [Wow!]
                       ...               
64927     [We, grew, closer, every, day.]
64928     [We, had, a, storm, yesterday.]
64929     [We, had, fun, at, Disneyland.]
64930    [We, had, lots, of, fun, today.]
64931          [We, had, no, drinking, w]
Name: English words/sentences, Length: 64932, dtype: object

In [8]:
data['French words/sentences count'] = data['French words/sentences'].str.split().str.len()


In [9]:
data = data[(data['English words/sentences count']<6)&(data['French words/sentences count']<6)]

In [10]:
data

English words/sentences              French words/sentences  \
0                            Hi.                              Salut!   
1                           Run!                             Cours !   
2                           Run!                            Courez !   
3                           Who?                               Qui ?   
4                           Wow!                          Ça alors !   
...                          ...                                 ...   
64906  We don't need it anymore.        Nous n'en avons plus besoin.   
64907  We don't need it anymore.       Nous n'en avons plus l'usage.   
64918  We elected him president.         Nous l'avons élu président.   
64919  We elected him president.            Nous l'élûmes président.   
64927  We grew closer every day.  Nous nous approchâmes chaque jour.   

       English words/sentences count  French words/sentences count  
0                                  1                           1.0  
1                                  1                           2.0  
2                                  1                           2.0  
3                                  1                           2.0  
4                                  1                           3.0  
...                              ...                           ...  
64906                              5                           5.0  
64907                              5                           5.0  
64918                              4                           4.0  
64919                              4                           3.0  
64927                              5                           5.0  

[46002 rows x 4 columns]

In [11]:
data = data.drop_duplicates()

In [12]:
data

English words/sentences              French words/sentences  \
0                            Hi.                              Salut!   
1                           Run!                             Cours !   
2                           Run!                            Courez !   
3                           Who?                               Qui ?   
4                           Wow!                          Ça alors !   
...                          ...                                 ...   
64906  We don't need it anymore.        Nous n'en avons plus besoin.   
64907  We don't need it anymore.       Nous n'en avons plus l'usage.   
64918  We elected him president.         Nous l'avons élu président.   
64919  We elected him president.            Nous l'élûmes président.   
64927  We grew closer every day.  Nous nous approchâmes chaque jour.   

       English words/sentences count  French words/sentences count  
0                                  1                           1.0  
1                                  1                           2.0  
2                                  1                           2.0  
3                                  1                           2.0  
4                                  1                           3.0  
...                              ...                           ...  
64906                              5                           5.0  
64907                              5                           5.0  
64918                              4                           4.0  
64919                              4                           3.0  
64927                              5                           5.0  

[46002 rows x 4 columns]

In [13]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(data, test_size = 0.2)


In [14]:
train["English words/sentences count"].max()

5

In [15]:
train["French words/sentences count"].max()

5.0

In [16]:
train, valid = train_test_split(train, test_size = 0.2)

In [17]:
freq_x=train['English words/sentences'].str.split(expand=True).stack().value_counts().reset_index()
freq_y=train['French words/sentences'].str.split(expand=True).stack().value_counts().reset_index()
freq_x.to_csv('English_freq.csv',index=False)
freq_y.to_csv('French_freq.csv',index=False)


In [18]:
freq_x=pd.read_csv('English_freq.csv')
freq_y=pd.read_csv('French_freq.csv')

In [19]:
freq_x

index     0
0             I  5452
1             a  2928
2           you  2697
3            is  2365
4           the  1722
...         ...   ...
8592      walls     1
8593      bare.     1
8594   Wouldn't     1
8595  overtime.     1
8596       egg.     1

[8597 rows x 2 columns]

In [20]:
freq_y

index     0
0                 ?  4389
1                Je  4196
2                Il  1973
3               est  1948
4               pas  1892
...             ...   ...
13813  Envoyez-nous     1
13814     l'époque.     1
13815    l'experte.     1
13816  M'aimez-vous     1
13817  Détenez-vous     1

[13818 rows x 2 columns]

In [21]:
def get_data(raw_lines):
    text = []
    for raw_line in raw_lines:
        text.append('<start>' + raw_line + '<end>')
    return text


In [22]:
    english_train = get_data(list(train['English words/sentences']))

In [23]:
english_train

["<start>That's not the answer.<end>",
 "<start>I'm so embarrassed.<end>",
 '<start>Could you explain that?<end>',
 "<start>You're arrogant.<end>",
 '<start>I study at the library.<end>',
 '<start>He is not so tall.<end>',
 '<start>Tom seems jealous.<end>',
 "<start>It's kind of late.<end>",
 "<start>It's at the corner.<end>",
 "<start>I'm more than happy.<end>",
 '<start>Why are you doing this?<end>',
 '<start>They must be punished.<end>',
 '<start>It must be there.<end>',
 '<start>You look tired.<end>',
 '<start>Where do you live?<end>',
 "<start>What don't you have?<end>",
 '<start>I know where she is.<end>',
 "<start>I'm new here.<end>",
 "<start>I should've said that.<end>",
 '<start>That house belongs to me.<end>',
 '<start>Go jump in the lake.<end>',
 '<start>That was your choice.<end>',
 '<start>Science is fun.<end>',
 '<start>I love summer.<end>',
 "<start>You can't help yourself.<end>",
 '<start>I am in Paris.<end>',
 '<start>Did you have fun?<end>',
 '<start>She had twins.<e

In [24]:
french_train = get_data(list(train['French words/sentences']))


In [25]:
french_train

["<start>Ce n'est pas la réponse.<end>",
 '<start>Je suis tellement embarrassé.<end>',
 '<start>Pourriez-vous expliquer cela\xa0?<end>',
 '<start>Tu es arrogante.<end>',
 "<start>J'étudie à la bibliothèque.<end>",
 "<start>Il n'est pas si grand.<end>",
 '<start>Tom semble jaloux.<end>',
 '<start>Il est plutôt tard.<end>',
 '<start>Ça se trouve au coin.<end>',
 "<start>Je suis plus qu'heureuse.<end>",
 '<start>Pourquoi fais-tu ça ?<end>',
 '<start>Ils doivent être punis.<end>',
 '<start>Ça doit être ici.<end>',
 '<start>Tu sembles fatigué.<end>',
 '<start>Où vivez-vous ?<end>',
 "<start>Que n'as-tu pas ?<end>",
 '<start>Je sais où elle est.<end>',
 '<start>Je suis nouveau, ici.<end>',
 "<start>J'aurais dû dire ça.<end>",
 '<start>Cette maison est la mienne.<end>',
 '<start>Va te noyer !<end>',
 "<start>C'était votre choix.<end>",
 '<start>La science est amusante.<end>',
 "<start>J'adore l'été.<end>",
 "<start>C'est plus fort que toi.<end>",
 '<start>Je suis à Paris.<end>',
 '<start>Vous

In [26]:
french_valid=get_data(list(valid['French words/sentences']))
English_valid=get_data(list(valid['English words/sentences']))


In [27]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

fre_token = Tokenizer(filters='', lower=False)
fre_token.fit_on_texts(french_train)
fre_tokenized = fre_token.texts_to_sequences(french_train)
fre_padded = pad_sequences(fre_tokenized, padding='post')

eng_token = Tokenizer(filters='', lower=False)
eng_token.fit_on_texts(english_train)
eng_tokenized = eng_token.texts_to_sequences(english_train)
eng_padded = pad_sequences(eng_tokenized, padding='post')


In [28]:
eng_padded

array([[  40,   23,    5,  554,    0],
       [   9,   81, 1284,    0,    0],
       [ 381,    3, 1764,  104,    0],
       ...,
       [ 133,    2,  591,    0,    0],
       [   7,    4,    2, 1122,    0],
       [  25,   16, 2640,    0,    0]], dtype=int32)

In [29]:
num_op_tokens = len(fre_token.word_index)
num_ip_tokens = len(eng_token.word_index)
max_len_op = fre_padded.shape[1]
num_len_ip = eng_padded.shape[1]

In [30]:
num_op_tokens

14617

In [31]:
num_ip_tokens

8623

In [32]:
max_len_op

5

In [33]:
num_len_ip

5

In [34]:
french_train[0]

"<start>Ce n'est pas la réponse.<end>"

In [35]:
fre_padded[0]

array([ 31,  35,   5,  19, 641], dtype=int32)

In [36]:
num_op_tokens

14617

In [37]:
num_ip_tokens

8623

In [38]:
max_len_op

5

In [39]:
num_len_ip

5

In [40]:
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

# Define the TextVectorization layer for English
english_vectorizer = TextVectorization(max_tokens=10407, output_sequence_length=7)
english_vectorizer.adapt(english_train)

# Preprocess the English data
english_train_vecs = english_vectorizer(english_train)



In [41]:
# Define the TextVectorization layer for French
french_vectorizer = TextVectorization(max_tokens=17228, output_sequence_length=7)
french_vectorizer.adapt(french_train)

# Preprocess the French data
french_train_vecs = french_vectorizer(french_train)

In [43]:
!pip install dill


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 2.4 MB/s eta 0:00:00


In [45]:
import dill as dpickle
import numpy as np
# Save the preprocessing objects and preprocessed data
# Save the vocabulary and configuration
with open('english_vectorizer_config.dpk1', 'wb') as f:
    dpickle.dump(english_vectorizer.get_config(), f)

with open('french_vectorizer_config.dpk1', 'wb') as f:
    dpickle.dump(french_vectorizer.get_config(), f)

# Save the preprocessed data
np.save('french_train_vecs.npy', french_train_vecs)
np.save('english_train_vecs.npy', english_train_vecs)

In [60]:
def load_decoder_inputs(decoder_np_vecs = 'french_train_vecs.npy'):
   vectorized_title = np.load(decoder_np_vecs)
   decoder_input_data = vectorized_title[:,:-1]
   decoder_target_data = vectorized_title[:,1:]
   print(f'shape of decoder input: {decoder_input_data.shape}')
   print(f'shape of decoder target: {decoder_target_data.shape}')
   return decoder_input_data,decoder_target_data
def load_encoder_inputs(encoder_np_vecs='english_train_vecs.npy'):

    vectorized_body = np.load(encoder_np_vecs)
    encoder_input_data = vectorized_body
    doc_length = encoder_input_data.shape[1]
    print(f'shape of encoder input: {encoder_input_data.shape}')
    return encoder_input_data,doc_length

In [61]:
def load_text_processor(fname='english_vectorizer_config.dpk1'):
    with open(fname,'rb') as f:
       config = dpickle.load(f)

    num_tokens = config['max_tokens']
    print(f'Size of vocabulary for {fname}: {num_tokens}')
    return num_tokens, config


In [62]:
import dill as dpickle

num_encoder_tokens, english_vectorizer_config = load_text_processor('english_vectorizer_config.dpk1')
num_decoder_tokens, french_vectorizer_config = load_text_processor('french_vectorizer_config.dpk1')


Size of vocabulary for english_vectorizer_config.dpk1: 10407
Size of vocabulary for french_vectorizer_config.dpk1: 17228


In [63]:
import numpy as np


encoder_input_data,doc_length = load_encoder_inputs('english_train_vecs.npy')
decoder_input_data,decoder_target_data = load_decoder_inputs('french_train_vecs.npy')


shape of encoder input: (29440, 7)
shape of decoder input: (29440, 6)
shape of decoder target: (29440, 6)


In [64]:
print('\noriginal string:\n',french_train[0])
print('after pre-processing:\n',decoder_input_data[0])



original string:
 <start>Ce n'est pas la réponse.<end>
after pre-processing:
 [ 31  35   6  16 665   0]


In [65]:
print('\noriginal string:\n',english_train[0],'\n')
print('after pre-processing:\n',encoder_input_data[0],'\n')


original string:
 <start>That's not the answer.<end> 

after pre-processing:
 [ 44  25   6 466   0   0   0] 



In [66]:
from keras.models import Model
from keras.layers import Input, LSTM, GRU, Dense,Embedding, Bidirectional,BatchNormalization
from keras import optimizers

In [75]:
latent_dim = 300
encoder_inputs = Input(shape = (doc_length,),name = 'Encoder-Input')

x = Embedding(num_encoder_tokens,latent_dim,name = 'Body-word-Embedding', mask_zero=False)(encoder_inputs)
x = BatchNormalization(name='Encoder-Batchnorm-1')(x)


_, state_h = GRU(latent_dim,return_state=True,name = 'Encoder_Last_GRU')(x)

encoder_model = Model(inputs=encoder_inputs,outputs=state_h,name='Encoder-Model')

seq2seq_encoder_out = encoder_model(encoder_inputs)

decoder_inputs = Input(shape=(None,),name='Decoder-Input')

dec_emb = Embedding(num_decoder_tokens,latent_dim,name='Decoder-word-Embedding', mask_zero = False)(decoder_inputs)
dec_bn  = BatchNormalization(name='Decoder-Batchnorm-1')(dec_emb)


decoder_gru = GRU(latent_dim,return_state=True,return_sequences=True,name='Decoder-GRU')
decoder_gru_output,_ = decoder_gru(dec_bn,initial_state=seq2seq_encoder_out)
x = BatchNormalization(name='Decoder-Batchnorm-2')(decoder_gru_output)


decoder_dense = Dense(num_decoder_tokens,activation='softmax',name = 'Final-Output-Dense')
decoder_outputs = decoder_dense(x)

seq2seq_Model = Model([encoder_inputs,decoder_inputs],decoder_outputs)

seq2seq_Model.compile(optimizer = optimizers.Nadam(lr=0.001),loss='sparse_categorical_crossentropy')

In [76]:
seq2seq_Model.summary()


Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 Decoder-Input (InputLayer)     [(None, None)]       0           []                               
                                                                                                  
 Decoder-word-Embedding (Embedd  (None, None, 300)   5168400     ['Decoder-Input[0][0]']          
 ing)                                                                                             
                                                                                                  
 Encoder-Input (InputLayer)     [(None, 7)]          0           []                               
                                                                                                  
 Decoder-Batchnorm-1 (BatchNorm  (None, None, 300)   1200        ['Decoder-word-Embedding[0]

In [96]:


from keras.callbacks import CSVLogger, ModelCheckpoint

script_name_base = 'tutorial_seq2seq'
csv_logger = CSVLogger('{:}.log'.format(script_name_base))
model_checkpoint = ModelCheckpoint('{}.epoch{{epoch:02d}}-val{{val_loss:.5f}}.hdf5'.format(script_name_base), save_best_only=True)

batch_size = 1200
epochs = 70
history = seq2seq_Model.fit([encoder_input_data, decoder_input_data], np.expand_dims(decoder_target_data, axis=-1),
    batch_size=batch_size,
    epochs=epochs,
    validation_split=0.12, callbacks=[csv_logger, model_checkpoint])



Epoch 1/70
 8/22 [=========>....................] - ETA: 1:37 - loss: 8.7297

KeyboardInterrupt: ignored

In [81]:
seq2seq_Model = Model([encoder_inputs,decoder_inputs],decoder_outputs)
seq2seq_Model.compile(optimizer=optimizers.Nadam(lr=0.001),loss='sparse_categorical_crossentropy')

In [82]:
seq2seq_Model.summary()


Model: "model_3"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 Decoder-Input (InputLayer)     [(None, None)]       0           []                               
                                                                                                  
 Decoder-word-Embedding (Embedd  (None, None, 300)   5168400     ['Decoder-Input[0][0]']          
 ing)                                                                                             
                                                                                                  
 Encoder-Input (InputLayer)     [(None, 7)]          0           []                               
                                                                                                  
 Decoder-Batchnorm-1 (BatchNorm  (None, None, 300)   1200        ['Decoder-word-Embedding[0]

In [98]:
from tensorflow.keras.models import load_model

# Replace 'your_model' with the actual name of your model class or load your model if not loaded already.
seq2seq_Model = your_model()

# Load the weights from the file
try:
    seq2seq_Model.load_weights('tutorial_seq2seq.epoch23-val1.78077.hdf5')
    print("Weights loaded successfully.")
except FileNotFoundError:
    print("File not found. Please provide the correct file path.")


NameError: ignored